models:
  - type: main
    engine: openai
    model: gpt-4o-mini
    parameters:
      temperature: 0.7
      max_tokens: 512

  - type: llama_guard
    engine: nim
    model: deepseek-ai/deepseek-r1
    parameters:
      api_key: "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"
      nim_base_url: "https://api.nvidia.com"

rails:
  input:
    flows: 
      - llama guard check input
      - greeting