models:
- type: main
  engine: nim
  model: gpt-oss-20b

- type: llama_guard
  engine: nim
  model: deepseek-ai/deepseek-r1
  parameters:
    api_key: "nvapi-xxxxx"
    nim_base_url: "https://ai.api.nvidia.com"

rails:
  input:
    flows: []